apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker0
  labels:
    app: kafka-broker0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      id: "0"
  template:
    metadata:
      labels:
        app: kafka        
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.12-2.2.1
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 9092
        resources:
          limits:
            cpu: "0.2"
            memory: "512Mi"
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
               
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-service"  

        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181

        - name: KAFKA_BROKER_ID
          value: "0"
          
  