apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongo-db"
  labels:
    app: "mongo-db"
spec:
  externalTrafficPolicy: "Local"
  ports:
    - protocol: TCP
      name: http      
      port: 27017
      targetPort: 27017
      nodePort: 30332
  type: "NodePort"
  selector:
    app: "mongo-db"