apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: tmongo-express
        image: mongo-express
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8081
        resources:
          limits:
            cpu: "0.2"
            memory: "512Mi"
        env:
        - name: ME_CONFIG_MONGODB_URL
          value: mongodb://root:example@mongo-db/

        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            configMapKeyRef:
              name: mongo-config-map
              key: mongo-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
     
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  type: LoadBalancer
  selector:
    app: mongo-express
  ports:
  - protocol: TCP
    name: http
    port: 8081
    targetPort: 8081
    nodePort: 30004