apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: http
    port: 3306
    targetPort: 3306
    nodePort: 30001
  selector:
    app: mysql
 