apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tech-challenge
  namespace: staging
  labels:
    app: app-tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-tech-challenge
  template:
    metadata:
      labels:
        app: app-tech-challenge
    spec:
      containers:
      - name: app-tech-challenge
        image: daniel36/techchallenge:1.4
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
        resources:
          limits:
            cpu: "0.2"
            memory: "512Mi"
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: DB_PASSWORD

        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name:  mysql-config-map
              key: mysql-server

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-name
              key: DB_NAME

        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-user
              key: DB_USERNAME