apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    # PostgreSQL configuration settings
    max_connections = 100
    ...
  init.sql: |
    -- Initialization SQL script
    CREATE DATABASE kong;
    ...