name: 'Terraform'

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  EKS-Dev:   
     needs: docker-pull-image 
     if: github.ref == 'refs/heads/main'  
     uses: develop/terraform-dev.yml    
     secrets: inherit

  #destroy-Dev:   
    # needs: docker-pull-image 
    # if: github.ref == 'refs/heads/main'  
    # uses: destroy/terraform-destroy.yml    
    # secrets: inherit
  
    
