name: 'Terraform'

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
permissions:
  contents: read

jobs:

  EKS-Dev: 
     if: github.ref == 'refs/heads/main'  
     uses: ./.github/workflows/terraform-dev.yml 
     secrets: inherit

  #destroy-Dev:   
    # needs: docker-pull-image 
    # if: github.ref == 'refs/heads/main'  
    # uses: destroy/terraform-destroy.yml    
    # secrets: inherit
  

