name: 'Terraform'

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
permissions:
  contents: read

jobs:

  #EKS-Dev: 
   #  if: github.ref == 'refs/heads/main'
    # uses: ./.github/workflows/terraform-dev.yml
     #secrets: inherit

  destroy-Dev:  
    
     if: github.ref == 'refs/heads/main'  
     uses: ./.github/workflows/terraform-destroy.yml    
     secrets: inherit
  

