name: kubernetes
on:
  workflow_call:
jobs:
  EKS:
    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@v3
     
    - name: configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ID_CHAVE_ACESSO }}
        aws-secret-access-key: ${{ secrets.CHAVE_SECRETA }}
        aws-region: us-east-1     
    

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
     
    - run: terraform -chdir=env/prod init    

    - run: terraform -chdir=env/prod destroy -auto-approve  
