name: kubernetes
on:
  workflow_call:
jobs:
  EKS:
    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@v3
     
    - name: configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ID_CHAVE_ACESSO }}
        aws-secret-access-key: ${{ secrets.CHAVE_SECRETA }}
        aws-region: us-east-1     
    

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
     

  

    
      if: github.ref == 'refs/heads/main'
   # - run: terraform -chdir=env/develop init
    
   # - run: terraform -chdir=env/develop apply -auto-approve

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v3
    
    - run: aws sts get-caller-identity
  
    - run: aws eks update-kubeconfig --region us-east-1 --name dev
  
    - run: kubectl get svc
    
    - run: kubectl apply -f kubernetes/mysql/mysql-secrets.yaml 
    - run: kubectl apply -f kubernetes/mysql/mysql-configmap.yaml 
    - run: kubectl apply -f ../../kubernetes/mysql/mysql-pv.yaml 
    - run: kubectl apply -f ../../kubernetes/mysql/mysql-service.yaml 
    - run: kubectl apply -f ../../kubernetes/mysql/mysql-statefulset.yaml

    - run: kubectl apply -f ../../kubernetes/mongo/mongo-secrets.yaml 
    - run: kubectl apply -f ../../kubernetes/mongo/mongo-configmap.yaml 
    - run: kubectl apply -f ../../kubernetes/mongo/mongo-pvc.yaml 
    - run: kubectl apply -f ../../kubernetes/mongo/mongo-service.yaml 
    - run: kubectl apply -f ../../kubernetes/mongo/mongo-statefulset.yaml
    - run: kubectl apply -f ../../kubernetes/mongo/mongo-express-deployment.yaml

    - run: kubectl apply -f ../../kubernetes/kafka/kafka-configmap.yaml
    - run: kubectl apply -f ../../kubernetes/kafka/zookeeper-deployment.yaml
    - run: kubectl apply -f ../../kubernetes/kafka/zookeeper-service.yaml
    - run: kubectl apply -f ../../kubernetes/kafka/kafka-deployment.yaml
    - run: kubectl apply -f ../../kubernetes/kafka/kafka-service.yaml
    - run: kubectl apply -f ../../kubernetes/kafka/kafka-ui-deployment.yaml


      
